### PR TITLE
Update NN weights with April work

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Review by annehaley — APPROVED** [review]
These changes look good. Do you have any data on how the inferences improved with this training?

**Comment by dzenanz** [comment]
Improvement is not significant. The training is a bit more consistent.
February-April change
Blue is old, red is new.

**Comment by annehaley** [comment]
Is there a known reason for the spike dip in R2 at ~700k steps?

**Comment by dzenanz** [comment]
That is first iteration of fold 3. Usually, the first few iterations have bad accuracy.

For each fold the best point is what we keep. And the convergence towards a certain value gives confidence.

**Pull request merged**
