### PR TITLE
Remove SNR and CNR from training and inference

### PR DESCRIPTION
**Pull request by dzenanz**
See analysis in #23.

### CODE REVIEW

**Comment by dzenanz** [comment]
@annehaley as this removes 2 columns out of 13, some adjustments in UI will be needed. Feel free to push them to this branch (`master` in my fork).

**Comment by annehaley** [comment]
> @annehaley as this removes 2 columns out of 13, some adjustments in UI will be needed. Feel free to push them to this branch (`master` in my fork).

Which UI changes do you mean? The current display component for Evaluation results does not include SNR or CNR.

**Comment by dzenanz** [comment]
Ah, you might be right. Can you check that it still works?

**Comment by annehaley** [comment]
Absolutely, I will be able to review it in a bit.

**Comment by dzenanz** [comment]
Judging by [regression_count = 1](https://github.com/dzenanz/miqa/blob/95fe0a56c4ef995d01f0cd53810f9fe99cc3a9fb/miqa/learning/nn_inference.py#L13) and [classes=regression_count + len(artifacts)](https://github.com/dzenanz/miqa/blob/95fe0a56c4ef995d01f0cd53810f9fe99cc3a9fb/miqa/learning/nn_inference.py#L79), the current model should have final layer size of 11, and that should be in the weight files too. Can you double check for gross errors (e.g. failures of git checkout)? If that does not turn up anything, we could have a meeting to debug it.

**Comment by annehaley** [comment]
Ah, you were right. It always seems to be a git-lfs problem. Once I was able to properly check out the changed model files, everything worked smoothly.

**Review by annehaley — APPROVED** [review]

**Pull request merged**
